version: "3"
services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV:-false}
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+asyncpg://postgres:postgres@localhost:5432/postgres"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - app_postgres
    volumes:
      - ./src:/usr/src/app/

  app_postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/app_pgdata"
    volumes:
      - ./docker/volumes/postgres/app_pgdata:/var/lib/postgresql/data/app_pgdata
    ports:
      - "5432:5432"
